name: luacheck

on: push

jobs:
  luacheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: build
      run: |
        sudo apt-get install luarocks
        luarocks install --local luacheck

    - name: luacheck
      run:
        /home/runner/.luarocks/bin/luacheck . --quiet --codes
